apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::533766786806:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-C05EJG425VR
      username: system:node:{{EC2PrivateDNSName}}

    - rolearn: arn:aws:iam::533766786806:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters

  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-16T18:23:07Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "829"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2f3a26cd-67b3-11ea-8b56-06b774221214
